PUT http://localhost:8080/events/1
Content-Type: application/json

{
    "name": "Truly first event",
    "description": "First true event",
    "location": "True location",
    "dateTime": "2025-01-01T15:30:00Z"
}